import { useEffect, useState } from 'react';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { localDateKey } from '../../date';
import { tokens } from '../../theme/tokens';
import { ConfirmActionSheet, DatePickerField, FieldCard, IconDisc, LedgerListCard, LedgerListRow, LedgerRowText, LedgerTrailing, PrimaryButton, ScreenSkeleton, SectionHeader, StatusChip } from '../../ui';
import type { Ready } from './LaborMvpApp';
import type { LaborV2Chemical, LaborV2ChemicalDetail, LaborV2ChemicalStatus } from './types';

type Props = { ready: Ready; notify: (text: string) => void; onBack: () => void; initialChemicalId?: string; initialIncludeArchived?: boolean };
const stateLabel: Record<LaborV2ChemicalStatus, string> = { available: 'มีอยู่', empty: 'หมดแล้ว', archived: 'เก็บไว้' };
const doseLabel = (chemical: Pick<LaborV2Chemical, 'referenceAmount' | 'referenceUnit' | 'referenceWaterLitres'>) => `${chemical.referenceAmount} ${chemical.referenceUnit} / ${chemical.referenceWaterLitres} ลิตร`;
const statusVariant = (status: LaborV2ChemicalStatus) => status === 'available' ? 'active' as const : status === 'empty' ? 'dueSoon' as const : 'archived' as const;

/** Own master-data home. It intentionally contains no stock subtraction or task-mix capture (Phase 2). */
export function ChemicalManagement({ ready, notify, onBack, initialChemicalId, initialIncludeArchived = false }: Props) {
  const [items, setItems] = useState<LaborV2Chemical[]>([]); const [includeArchived, setIncludeArchived] = useState(Boolean(initialChemicalId) || initialIncludeArchived); const [selectedId, setSelectedId] = useState<string | 'new' | null>(initialChemicalId ?? null); const [loading, setLoading] = useState(true);
  const load = async () => { setLoading(true); try { setItems(await ready.adapter.chemicals.list(includeArchived)); } catch { notify('เปิดคลังยาไม่สำเร็จ'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [ready.adapter, includeArchived]);
  if (selectedId) return <ChemicalDetail ready={ready} notify={notify} chemicalId={selectedId === 'new' ? null : selectedId} onBack={() => { setSelectedId(null); void load(); }} />;
  if (loading) return <ScreenSkeleton lines={3} />;
  const active = items.filter((item) => item.status !== 'archived'); const archived = items.filter((item) => item.status === 'archived'); const rows = includeArchived ? items : active;
  return <View style={styles.screen}><Pressable onPress={onBack}><Text style={styles.route}>‹ กลับไปจัดการ</Text></Pressable><FieldCard variant="raised" style={styles.hero}><IconDisc icon="chemical" size={44} tone="gold" /><View style={styles.heroText}><Text style={styles.eyebrow}>รายการเคมีเกษตร</Text><Text style={styles.title}>คลังยา / เคมี</Text><Text style={styles.muted}>เช็กแค่ว่ามีอยู่หรือหมดแล้ว ไม่ต้องนับสต็อก</Text></View></FieldCard><View style={styles.rowHeader}><SectionHeader title={`รายการใช้งาน (${active.length})`} /><Pressable onPress={() => setIncludeArchived((value) => !value)}><Text style={styles.route}>{includeArchived ? 'ซ่อนที่เก็บไว้' : `ดูที่เก็บไว้ (${archived.length})`}</Text></Pressable></View>{rows.length ? <LedgerListCard>{rows.map((item) => <Pressable key={item.id} onPress={() => setSelectedId(item.id)}><LedgerListRow><IconDisc icon="chemical" size={34} tone={item.status === 'available' ? 'sage' : 'gold'} /><LedgerRowText title={item.commonName} detail={`${doseLabel(item)} · เพิ่ม ${item.addedOn}${item.brandName ? ` · ${item.brandName}` : ''}`} /><LedgerTrailing><StatusChip label={stateLabel[item.status]} variant={statusVariant(item.status)} /></LedgerTrailing></LedgerListRow></Pressable>)}</LedgerListCard> : <FieldCard><Text style={styles.muted}>ยังไม่มีรายการ เพิ่มชื่อยาเมื่ออยากเก็บไว้ใช้ซ้ำ</Text></FieldCard>}<PrimaryButton label="+ เพิ่มยา / เคมี" onPress={() => setSelectedId('new')} /></View>;
}

function ChemicalDetail({ ready, notify, chemicalId, onBack }: { ready: Ready; notify: (text: string) => void; chemicalId: string | null; onBack: () => void }) {
  const [detail, setDetail] = useState<LaborV2ChemicalDetail | null>(null); const [commonName, setCommonName] = useState(''); const [brandName, setBrandName] = useState(''); const [chemicalGroup, setChemicalGroup] = useState(''); const [detailText, setDetailText] = useState(''); const [amount, setAmount] = useState(''); const [unit, setUnit] = useState(''); const [water, setWater] = useState(''); const [addedOn, setAddedOn] = useState(localDateKey()); const [reason, setReason] = useState(''); const [editing, setEditing] = useState(chemicalId === null); const [confirm, setConfirm] = useState<'empty' | 'available' | 'archive' | 'restore' | null>(null); const [saving, setSaving] = useState(false);
  const load = async () => { if (!chemicalId) return; try { const next = await ready.adapter.chemicals.detail(chemicalId); setDetail(next); setCommonName(next.commonName); setBrandName(next.brandName); setChemicalGroup(next.chemicalGroup); setDetailText(next.detail); setAmount(String(next.referenceAmount)); setUnit(next.referenceUnit); setWater(String(next.referenceWaterLitres)); setAddedOn(next.addedOn); } catch { notify('เปิดรายละเอียดยาไม่สำเร็จ'); } };
  useEffect(() => { void load(); }, [chemicalId, ready.adapter]);
  const parsed = () => { const referenceAmount = Number(amount); const referenceWaterLitres = Number(water); if (!commonName.trim() || !unit.trim() || !Number.isFinite(referenceAmount) || referenceAmount <= 0 || !Number.isFinite(referenceWaterLitres) || referenceWaterLitres <= 0) { notify('กรอกชื่อยา อัตราใช้ หน่วย และปริมาณน้ำอ้างอิงให้ครบ'); return null; } return { referenceAmount, referenceWaterLitres }; };
  const save = async () => { const dose = parsed(); if (!dose) return; if (chemicalId && !reason.trim()) return notify('บอกเหตุผลที่แก้ไขก่อนบันทึก'); setSaving(true); try { const values = { commonName: commonName.trim(), brandName: brandName.trim() || undefined, chemicalGroup: chemicalGroup.trim() || undefined, detail: detailText.trim() || undefined, referenceAmount: dose.referenceAmount, referenceUnit: unit.trim(), referenceWaterLitres: dose.referenceWaterLitres, addedOn }; if (chemicalId) await ready.adapter.chemicals.update(chemicalId, { ...values, reason: reason.trim() }); else await ready.adapter.chemicals.create(values); setReason(''); setEditing(false); notify(chemicalId ? 'บันทึกการแก้ไขยา พร้อมประวัติแล้ว' : 'เพิ่มยา / เคมีแล้ว'); if (!chemicalId) onBack(); else await load(); } catch (error) { notify(error instanceof Error ? error.message : 'บันทึกยาไม่สำเร็จ'); } finally { setSaving(false); } };
  const changeStatus = async () => { if (!detail || !confirm || !reason.trim()) return notify('บอกเหตุผลก่อนยืนยัน'); setSaving(true); try { if (confirm === 'empty') await ready.adapter.chemicals.markEmpty(detail.id, reason.trim()); if (confirm === 'available') await ready.adapter.chemicals.restoreAvailable(detail.id, reason.trim()); if (confirm === 'archive') await ready.adapter.chemicals.archive(detail.id, reason.trim()); if (confirm === 'restore') await ready.adapter.chemicals.restore(detail.id, reason.trim()); setConfirm(null); setReason(''); await load(); notify('เปลี่ยนสถานะรายการแล้ว ประวัติเดิมยังอยู่ครบ'); } catch (error) { notify(error instanceof Error ? error.message : 'เปลี่ยนสถานะยาไม่สำเร็จ'); } finally { setSaving(false); } };
  if (chemicalId && !detail) return <ScreenSkeleton lines={3} />;
  const archived = detail?.status === 'archived';
  return <View style={styles.screen}>
    <Pressable onPress={onBack}><Text style={styles.route}>‹ กลับไปคลังยา / เคมี</Text></Pressable>
    {detail ? <FieldCard variant="raised" style={styles.hero}><IconDisc icon="chemical" size={44} tone={detail.status === 'available' ? 'sage' : 'gold'} /><View style={styles.heroText}><Text style={styles.eyebrow}>{stateLabel[detail.status]}</Text><Text style={styles.title}>{detail.commonName}</Text><Text style={styles.muted}>{doseLabel(detail)}{detail.brandName ? ` · ${detail.brandName}` : ''}</Text><Text style={styles.caption}>เพิ่ม {detail.addedOn}{detail.chemicalGroup ? ` · กลุ่มยา ${detail.chemicalGroup}` : ''}{detail.lastUsedOn ? ` · ใช้ล่าสุด ${detail.lastUsedOn}` : ' · ยังไม่มีบันทึกการใช้'}</Text></View></FieldCard> : <SectionHeader title="เพิ่มยา / เคมี" />}
    {(!archived || editing) ? <FieldCard style={styles.form}><SectionHeader title={editing ? (chemicalId ? 'แก้ไขข้อมูลยา' : 'ข้อมูลยาใหม่') : 'ข้อมูลยา'} /><TextInput style={styles.input} value={commonName} onChangeText={setCommonName} placeholder="ชื่อสามัญ (เช่น แมนโคเซบ)" /><TextInput style={styles.input} value={brandName} onChangeText={setBrandName} placeholder="ชื่อแบรนด์ (ไม่บังคับ)" /><TextInput style={styles.input} value={chemicalGroup} onChangeText={setChemicalGroup} placeholder="กลุ่มยา (ไม่บังคับ เช่น M03)" /><View style={styles.dose}><TextInput style={[styles.input, styles.amount]} keyboardType="decimal-pad" value={amount} onChangeText={setAmount} placeholder="อัตราใช้" /><TextInput style={[styles.input, styles.unit]} value={unit} onChangeText={setUnit} placeholder="หน่วย เช่น g" /></View><TextInput style={styles.input} keyboardType="decimal-pad" value={water} onChangeText={setWater} placeholder="ต่อน้ำกี่ลิตร (เช่น 200)" /><DatePickerField label="วันที่เพิ่มรายการ" value={addedOn} onChange={setAddedOn} /><TextInput style={styles.input} value={detailText} onChangeText={setDetailText} placeholder="รายละเอียดเพิ่มเติม (ไม่บังคับ)" />{chemicalId ? <TextInput style={styles.input} value={reason} onChangeText={setReason} placeholder="เหตุผลที่แก้ไข (จำเป็น)" /> : null}{editing ? <PrimaryButton disabled={saving} label={saving ? 'กำลังบันทึก…' : 'บันทึกยา / เคมี'} onPress={() => void save()} /> : <PrimaryButton label="แก้ไขข้อมูลยา" variant="secondary" onPress={() => setEditing(true)} />}</FieldCard> : null}
    {detail && !editing ? <><SectionHeader title={`ประวัติการใช้ (${detail.usages.length})`} />{detail.usages.length ? <LedgerListCard>{detail.usages.map((usage, index) => <LedgerListRow key={`${usage.taskId}-${index}`}><IconDisc icon="work" size={30} tone="sage" /><LedgerRowText title={usage.taskTitle} detail={`${usage.workDate} · น้ำ ${usage.waterLitres} ลิตร · สูตรที่บันทึก ${usage.referenceAmount} ${usage.referenceUnit} / ${usage.referenceWaterLitres} ลิตร`} /><LedgerTrailing><Text style={styles.title}>{usage.calculatedAmount} {usage.referenceUnit}</Text>{usage.wasMarkedEmpty ? <StatusChip label="หมดแล้ว" variant="dueSoon" /> : null}</LedgerTrailing></LedgerListRow>)}</LedgerListCard> : <FieldCard><Text style={styles.muted}>ยังไม่มีงานที่บันทึกว่าใช้รายการนี้</Text></FieldCard>}<SectionHeader title="ประวัติรายการ" /><LedgerListCard>{detail.revisions.map((revision) => <LedgerListRow key={revision.id}><IconDisc icon="record" size={30} tone={revision.action === 'marked_empty' || revision.action === 'archived' ? 'gold' : 'sage'} /><LedgerRowText title={revision.action === 'created' ? 'เพิ่มรายการ' : revision.action === 'updated' ? 'แก้ไขข้อมูล' : revision.action === 'marked_empty' ? 'ระบุว่าหมดแล้ว' : revision.action === 'restored_available' ? 'ระบุว่ามีอยู่' : revision.action === 'archived' ? 'เก็บรายการไว้' : 'นำรายการกลับมา'} detail={`${revision.createdAt.slice(0, 10)}${revision.reason ? ` · ${revision.reason}` : ''}`} /><LedgerTrailing><Text style={styles.caption}>ครั้งที่ {revision.revision}</Text></LedgerTrailing></LedgerListRow>)}</LedgerListCard>{detail.status === 'available' ? <><TextInput style={styles.input} value={reason} onChangeText={setReason} placeholder="เหตุผลที่ระบุว่าหมดแล้ว (จำเป็น)" /><PrimaryButton label="ระบุว่าหมดแล้ว" variant="secondary" onPress={() => setConfirm('empty')} /><PrimaryButton label="เก็บรายการนี้ไว้" variant="secondary" onPress={() => setConfirm('archive')} /></> : detail.status === 'empty' ? <><TextInput style={styles.input} value={reason} onChangeText={setReason} placeholder="เหตุผลที่ระบุว่ามีอยู่ (จำเป็น)" /><PrimaryButton label="ระบุว่ามีอยู่" onPress={() => setConfirm('available')} /><PrimaryButton label="เก็บรายการนี้ไว้" variant="secondary" onPress={() => setConfirm('archive')} /></> : <><TextInput style={styles.input} value={reason} onChangeText={setReason} placeholder="เหตุผลที่นำรายการกลับมา (จำเป็น)" /><PrimaryButton label="นำรายการกลับมาใช้" onPress={() => setConfirm('restore')} /></>}</> : null}
    <ConfirmActionSheet visible={confirm !== null} title="ยืนยันการเปลี่ยนสถานะ" detail="รายการเดิมจะไม่ถูกลบ และบันทึกเหตุผลไว้ในประวัติ" cancelLabel="กลับไปตรวจ" confirmLabel="ยืนยัน" confirmDisabled={saving} onCancel={() => setConfirm(null)} onConfirm={() => void changeStatus()} />
  </View>;
}

const styles = StyleSheet.create({ screen: { gap: 16 }, hero: { alignItems: 'flex-start', flexDirection: 'row', gap: 12 }, heroText: { flex: 1, gap: 3, minWidth: 0 }, title: { color: tokens.color.text.primary, fontSize: tokens.typography.h2.size, fontWeight: '800' }, eyebrow: { color: tokens.color.text.muted, fontSize: tokens.typography.metadata.size, fontWeight: '700' }, muted: { color: tokens.color.text.muted, fontSize: tokens.typography.body.size, lineHeight: 23 }, caption: { color: tokens.color.text.muted, fontSize: tokens.typography.caption.size }, route: { color: tokens.color.primary.green, fontSize: tokens.typography.metadata.size, fontWeight: '800' }, rowHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' }, form: { gap: 12 }, input: { backgroundColor: tokens.color.surface.card, borderColor: tokens.color.border.soft, borderRadius: tokens.radius.row, borderWidth: 1, color: tokens.color.text.primary, flex: 1, fontSize: tokens.typography.body.size, minHeight: 48, paddingHorizontal: 14 }, dose: { flexDirection: 'row', gap: 8 }, amount: { flex: 1 }, unit: { flex: 1 } });
