import type { LaborMvpReadModel, LaborPreviewWebProjections } from './types';

// Generated by scripts/generate-labor-preview-web-fixture.ts. Do not hand-edit.
export const LABOR_PREVIEW_WEB_READ_MODEL: LaborMvpReadModel = {
  "people": [
    {
      "id": "labor-preview-chon",
      "displayName": "น้าชล",
      "specialty": "งานรายชั่วโมง",
      "phone": "",
      "note": "",
      "archivedAt": null,
      "dueSatang": 0,
      "paidSatang": 0,
      "remainingSatang": 0,
      "grossEarnedSatang": 0,
      "cashPaidSatang": 0,
      "wageRemainingSatang": 0,
      "advanceIssuedSatang": 100000,
      "advanceRecoveredSatang": 0,
      "advanceRemainingSatang": 100000
    },
    {
      "id": "labor-preview-phuang",
      "displayName": "พี่พวง",
      "specialty": "กรอกถุงเพาะชำ",
      "phone": "",
      "note": "",
      "archivedAt": null,
      "dueSatang": 0,
      "paidSatang": 0,
      "remainingSatang": 0,
      "grossEarnedSatang": 0,
      "cashPaidSatang": 0,
      "wageRemainingSatang": 0,
      "advanceIssuedSatang": 0,
      "advanceRecoveredSatang": 0,
      "advanceRemainingSatang": 0
    },
    {
      "id": "labor-preview-suda",
      "displayName": "พี่สุ",
      "specialty": "งานรายวันและกรอกถุง",
      "phone": "",
      "note": "",
      "archivedAt": null,
      "dueSatang": 35000,
      "paidSatang": 35000,
      "remainingSatang": 0,
      "grossEarnedSatang": 35000,
      "cashPaidSatang": 35000,
      "wageRemainingSatang": 0,
      "advanceIssuedSatang": 0,
      "advanceRecoveredSatang": 0,
      "advanceRemainingSatang": 0
    }
  ],
  "payables": [
    {
      "id": "labor-preview-daily-payable-1",
      "jobId": "labor-preview-daily",
      "jobTitle": "ตัดหญ้ารอบบ้าน",
      "workDate": "2026-08-02",
      "personId": "labor-preview-suda",
      "dueSatang": 35000,
      "paidSatang": 35000,
      "recoveredSatang": 0,
      "remainingSatang": 0,
      "kind": "normal"
    }
  ],
  "payments": [
    {
      "id": "labor-preview-daily-payment",
      "personId": "labor-preview-suda",
      "paymentDate": "2026-08-02",
      "method": "cash",
      "note": "",
      "totalSatang": 35000,
      "currentRevision": 1,
      "allocations": [
        {
          "id": "labor-preview-daily-payment-allocation-1",
          "payableId": "labor-preview-daily-payable-1",
          "amountSatang": 35000
        }
      ]
    }
  ],
  "timeline": [
    {
      "id": "labor-preview-timeline-1",
      "entityType": "person",
      "entityId": "labor-preview-suda",
      "action": "worker_created",
      "occurredAt": "2026-08-02T08:00:00.000Z",
      "reason": null,
      "before": null,
      "after": {
        "id": "labor-preview-suda",
        "displayName": "พี่สุ",
        "role": "worker",
        "specialty": "งานรายวันและกรอกถุง",
        "phone": "",
        "note": ""
      },
      "personId": "labor-preview-suda",
      "laborJobId": null
    },
    {
      "id": "labor-preview-timeline-2",
      "entityType": "person",
      "entityId": "labor-preview-phuang",
      "action": "worker_created",
      "occurredAt": "2026-08-02T08:00:01.000Z",
      "reason": null,
      "before": null,
      "after": {
        "id": "labor-preview-phuang",
        "displayName": "พี่พวง",
        "role": "worker",
        "specialty": "กรอกถุงเพาะชำ",
        "phone": "",
        "note": ""
      },
      "personId": "labor-preview-phuang",
      "laborJobId": null
    },
    {
      "id": "labor-preview-timeline-3",
      "entityType": "person",
      "entityId": "labor-preview-chon",
      "action": "worker_created",
      "occurredAt": "2026-08-02T08:00:02.000Z",
      "reason": null,
      "before": null,
      "after": {
        "id": "labor-preview-chon",
        "displayName": "น้าชล",
        "role": "worker",
        "specialty": "งานรายชั่วโมง",
        "phone": "",
        "note": ""
      },
      "personId": "labor-preview-chon",
      "laborJobId": null
    },
    {
      "id": "labor-preview-timeline-4",
      "entityType": "labor_job",
      "entityId": "labor-preview-daily",
      "action": "normal_work_created",
      "occurredAt": "2026-08-02T08:01:00.000Z",
      "reason": null,
      "before": null,
      "after": {
        "id": "labor-preview-daily",
        "title": "ตัดหญ้ารอบบ้าน",
        "workDate": "2026-08-02",
        "plotId": null,
        "kind": "normal",
        "participants": [
          {
            "personId": "labor-preview-suda",
            "dueSatang": 35000,
            "payType": "daily"
          }
        ]
      },
      "personId": null,
      "laborJobId": "labor-preview-daily"
    },
    {
      "id": "labor-preview-timeline-5",
      "entityType": "labor_payment",
      "entityId": "labor-preview-daily-payment",
      "action": "payment_posted",
      "occurredAt": "2026-08-02T08:01:01.000Z",
      "reason": null,
      "before": null,
      "after": {
        "id": "labor-preview-daily-payment",
        "personId": "labor-preview-suda",
        "paymentDate": "2026-08-02",
        "method": "cash",
        "note": "",
        "totalSatang": 35000,
        "currentRevision": 1,
        "allocations": [
          {
            "id": "labor-preview-daily-payment-allocation-1",
            "payableId": "labor-preview-daily-payable-1",
            "amountSatang": 35000
          }
        ]
      },
      "personId": "labor-preview-suda",
      "laborJobId": null
    },
    {
      "id": "labor-preview-timeline-6",
      "entityType": "labor_job",
      "entityId": "labor-preview-group-piece",
      "action": "group_piece_work_recorded",
      "occurredAt": "2026-08-02T08:02:00.000Z",
      "reason": null,
      "before": null,
      "after": {
        "title": "กรอกถุงเพาะชำ",
        "workDate": "2026-08-01",
        "settlementRoute": "group",
        "quantityMilli": 4125000,
        "unitLabel": "ถุง",
        "rateSatang": 100,
        "originalDueSatang": 412500,
        "group": {
          "id": "labor-preview-group-piece-settlement",
          "jobId": "labor-preview-group-piece",
          "originalDueSatang": 412500,
          "paidSatang": 0,
          "remainingSatang": 412500,
          "status": "open",
          "collectorPersonId": null,
          "collectorLabel": "พี่สุรับแทนชุดงาน",
          "memberPersonIds": [
            "labor-preview-suda",
            "labor-preview-phuang"
          ],
          "receipts": []
        }
      },
      "personId": null,
      "laborJobId": "labor-preview-group-piece"
    },
    {
      "id": "labor-preview-timeline-7",
      "entityType": "labor_job",
      "entityId": "labor-preview-group-piece",
      "action": "settlement_group_created",
      "occurredAt": "2026-08-02T08:02:00.000Z",
      "reason": null,
      "before": null,
      "after": {
        "id": "labor-preview-group-piece-settlement",
        "jobId": "labor-preview-group-piece",
        "originalDueSatang": 412500,
        "paidSatang": 0,
        "remainingSatang": 412500,
        "status": "open",
        "collectorPersonId": null,
        "collectorLabel": "พี่สุรับแทนชุดงาน",
        "memberPersonIds": [
          "labor-preview-suda",
          "labor-preview-phuang"
        ],
        "receipts": []
      },
      "personId": null,
      "laborJobId": "labor-preview-group-piece"
    },
    {
      "id": "labor-preview-timeline-8",
      "entityType": "labor_job",
      "entityId": "labor-preview-group-piece",
      "action": "settlement_group_receipt_posted",
      "occurredAt": "2026-08-02T08:02:01.000Z",
      "reason": null,
      "before": {
        "id": "labor-preview-group-piece-settlement",
        "jobId": "labor-preview-group-piece",
        "originalDueSatang": 412500,
        "paidSatang": 0,
        "remainingSatang": 412500,
        "status": "open",
        "collectorPersonId": null,
        "collectorLabel": "พี่สุรับแทนชุดงาน",
        "memberPersonIds": [
          "labor-preview-suda",
          "labor-preview-phuang"
        ],
        "receipts": []
      },
      "after": {
        "group": {
          "id": "labor-preview-group-piece-settlement",
          "jobId": "labor-preview-group-piece",
          "originalDueSatang": 412500,
          "paidSatang": 412500,
          "remainingSatang": 0,
          "status": "settled",
          "collectorPersonId": null,
          "collectorLabel": "พี่สุรับแทนชุดงาน",
          "memberPersonIds": [
            "labor-preview-suda",
            "labor-preview-phuang"
          ],
          "receipts": [
            {
              "id": "labor-preview-group-receipt",
              "settlementGroupId": "labor-preview-group-piece-settlement",
              "receiptDate": "2026-08-02",
              "amountSatang": 412500,
              "method": "cash",
              "note": "",
              "currentRevision": 1,
              "status": "posted"
            }
          ]
        },
        "receipt": {
          "id": "labor-preview-group-receipt",
          "settlementGroupId": "labor-preview-group-piece-settlement",
          "receiptDate": "2026-08-02",
          "amountSatang": 412500,
          "method": "cash",
          "note": "",
          "currentRevision": 1,
          "status": "posted"
        }
      },
      "personId": null,
      "laborJobId": "labor-preview-group-piece"
    },
    {
      "id": "labor-preview-timeline-9",
      "entityType": "person",
      "entityId": "labor-preview-chon",
      "action": "worker_advance_issued",
      "occurredAt": "2026-08-02T08:03:00.000Z",
      "reason": null,
      "before": null,
      "after": {
        "id": "labor-preview-chon-advance",
        "personId": "labor-preview-chon",
        "advanceDate": "2026-08-01",
        "amountSatang": 100000,
        "recoveredSatang": 0,
        "remainingSatang": 100000,
        "method": "cash",
        "note": "ตัวอย่างเงินเบิก",
        "currentRevision": 1,
        "status": "posted"
      },
      "personId": "labor-preview-chon",
      "laborJobId": null
    }
  ],
  "contracts": [],
  "legacySources": [],
  "legacyBalances": [],
  "settlementGroups": [
    {
      "id": "labor-preview-group-piece-settlement",
      "jobId": "labor-preview-group-piece",
      "originalDueSatang": 412500,
      "paidSatang": 412500,
      "remainingSatang": 0,
      "status": "settled",
      "collectorPersonId": null,
      "collectorLabel": "พี่สุรับแทนชุดงาน",
      "memberPersonIds": [
        "labor-preview-suda",
        "labor-preview-phuang"
      ],
      "receipts": [
        {
          "id": "labor-preview-group-receipt",
          "settlementGroupId": "labor-preview-group-piece-settlement",
          "receiptDate": "2026-08-02",
          "amountSatang": 412500,
          "method": "cash",
          "note": "",
          "currentRevision": 1,
          "status": "posted"
        }
      ]
    }
  ],
  "workBasisSnapshots": [
    {
      "id": "labor-preview-daily-basis-1",
      "jobId": "labor-preview-daily",
      "settlementRoute": "individual",
      "basisKind": "daily",
      "stage": "recorded",
      "personId": "labor-preview-suda",
      "rateSatang": 35000,
      "quantityMilli": 1000,
      "durationMinutes": null,
      "unitLabel": "วัน",
      "totalSatang": 35000,
      "note": "",
      "createdAt": "2026-08-02T08:01:00.000Z"
    },
    {
      "id": "labor-preview-group-piece-basis-1",
      "jobId": "labor-preview-group-piece",
      "settlementRoute": "group",
      "basisKind": "piece",
      "stage": "recorded",
      "personId": null,
      "rateSatang": 100,
      "quantityMilli": 4125000,
      "durationMinutes": null,
      "unitLabel": "ถุง",
      "totalSatang": 412500,
      "note": "",
      "createdAt": "2026-08-02T08:02:00.000Z"
    }
  ],
  "advances": [
    {
      "id": "labor-preview-chon-advance",
      "personId": "labor-preview-chon",
      "advanceDate": "2026-08-01",
      "amountSatang": 100000,
      "recoveredSatang": 0,
      "remainingSatang": 100000,
      "method": "cash",
      "note": "ตัวอย่างเงินเบิก",
      "currentRevision": 1,
      "status": "posted"
    }
  ],
  "advanceDeductions": []
};

export const LABOR_PREVIEW_WEB_PROJECTIONS: LaborPreviewWebProjections = {
  "today": {
    "date": "2026-08-02",
    "day": {
      "date": "2026-08-02",
      "events": [
        {
          "id": "work:labor-preview-daily",
          "eventType": "work",
          "effectiveDate": "2026-08-02",
          "recordedAt": "2026-08-02T08:01:00.000Z",
          "label": "ตัดหญ้ารอบบ้าน",
          "detail": "พี่สุ",
          "jobId": "labor-preview-daily",
          "jobIds": [
            "labor-preview-daily"
          ],
          "personId": null,
          "personIds": [
            "labor-preview-suda"
          ],
          "settlementGroupId": null,
          "settlementRoute": "individual",
          "paymentState": "paid",
          "amountSatang": 0,
          "dueSatang": 35000,
          "remainingSatang": 0
        },
        {
          "id": "payment:labor-preview-daily-payment",
          "eventType": "individual_payment",
          "effectiveDate": "2026-08-02",
          "recordedAt": "2026-08-02T08:01:01.000Z",
          "label": "จ่ายค่าแรง · พี่สุ",
          "detail": "ตัดหญ้ารอบบ้าน",
          "jobId": "labor-preview-daily",
          "jobIds": [
            "labor-preview-daily"
          ],
          "personId": "labor-preview-suda",
          "personIds": [
            "labor-preview-suda"
          ],
          "settlementGroupId": null,
          "settlementRoute": "individual",
          "paymentState": "not_applicable",
          "amountSatang": 35000,
          "dueSatang": 0,
          "remainingSatang": 0
        },
        {
          "id": "group-receipt:labor-preview-group-receipt",
          "eventType": "group_receipt",
          "effectiveDate": "2026-08-02",
          "recordedAt": "2026-08-02T08:02:01.000Z",
          "label": "รับเงินชุดงาน · กรอกถุงเพาะชำ",
          "detail": "พี่สุรับแทนชุดงาน",
          "jobId": "labor-preview-group-piece",
          "jobIds": [
            "labor-preview-group-piece"
          ],
          "personId": null,
          "personIds": [],
          "settlementGroupId": "labor-preview-group-piece-settlement",
          "settlementRoute": "group",
          "paymentState": "not_applicable",
          "amountSatang": 412500,
          "dueSatang": 0,
          "remainingSatang": 0
        }
      ],
      "workCount": 1,
      "workDueSatang": 35000,
      "individualPaymentSatang": 35000,
      "groupReceiptSatang": 412500,
      "advanceIssuedSatang": 0,
      "advanceRecoveredSatang": 0,
      "contractProgressCount": 0,
      "contractCompletionCount": 0,
      "contractDeadlineCount": 0
    },
    "unpaidPeople": [],
    "advanceAttentionPeople": [
      {
        "id": "labor-preview-chon",
        "displayName": "น้าชล",
        "specialty": "งานรายชั่วโมง",
        "phone": "",
        "note": "",
        "archivedAt": null,
        "dueSatang": 0,
        "paidSatang": 0,
        "remainingSatang": 0,
        "grossEarnedSatang": 0,
        "cashPaidSatang": 0,
        "wageRemainingSatang": 0,
        "advanceIssuedSatang": 100000,
        "advanceRecoveredSatang": 0,
        "advanceRemainingSatang": 100000
      }
    ]
  },
  "calendar": {
    "startDate": "2026-08-01",
    "endDate": "2026-08-31",
    "days": [
      {
        "date": "2026-08-01",
        "events": [
          {
            "id": "work:labor-preview-group-piece",
            "eventType": "work",
            "effectiveDate": "2026-08-01",
            "recordedAt": "2026-08-02T08:02:00.000Z",
            "label": "กรอกถุงเพาะชำ",
            "detail": "พี่สุ · พี่พวง",
            "jobId": "labor-preview-group-piece",
            "jobIds": [
              "labor-preview-group-piece"
            ],
            "personId": null,
            "personIds": [
              "labor-preview-suda",
              "labor-preview-phuang"
            ],
            "settlementGroupId": "labor-preview-group-piece-settlement",
            "settlementRoute": "group",
            "paymentState": "paid",
            "amountSatang": 0,
            "dueSatang": 412500,
            "remainingSatang": 0
          },
          {
            "id": "advance:labor-preview-chon-advance",
            "eventType": "advance",
            "effectiveDate": "2026-08-01",
            "recordedAt": "2026-08-02T08:03:00.000Z",
            "label": "เงินเบิก · น้าชล",
            "detail": "ตัวอย่างเงินเบิก",
            "jobId": null,
            "jobIds": [],
            "personId": "labor-preview-chon",
            "personIds": [
              "labor-preview-chon"
            ],
            "settlementGroupId": null,
            "settlementRoute": null,
            "paymentState": "not_applicable",
            "amountSatang": 100000,
            "dueSatang": 0,
            "remainingSatang": 0
          }
        ],
        "workCount": 1,
        "workDueSatang": 412500,
        "individualPaymentSatang": 0,
        "groupReceiptSatang": 0,
        "advanceIssuedSatang": 100000,
        "advanceRecoveredSatang": 0,
        "contractProgressCount": 0,
        "contractCompletionCount": 0,
        "contractDeadlineCount": 0
      },
      {
        "date": "2026-08-02",
        "events": [
          {
            "id": "work:labor-preview-daily",
            "eventType": "work",
            "effectiveDate": "2026-08-02",
            "recordedAt": "2026-08-02T08:01:00.000Z",
            "label": "ตัดหญ้ารอบบ้าน",
            "detail": "พี่สุ",
            "jobId": "labor-preview-daily",
            "jobIds": [
              "labor-preview-daily"
            ],
            "personId": null,
            "personIds": [
              "labor-preview-suda"
            ],
            "settlementGroupId": null,
            "settlementRoute": "individual",
            "paymentState": "paid",
            "amountSatang": 0,
            "dueSatang": 35000,
            "remainingSatang": 0
          },
          {
            "id": "payment:labor-preview-daily-payment",
            "eventType": "individual_payment",
            "effectiveDate": "2026-08-02",
            "recordedAt": "2026-08-02T08:01:01.000Z",
            "label": "จ่ายค่าแรง · พี่สุ",
            "detail": "ตัดหญ้ารอบบ้าน",
            "jobId": "labor-preview-daily",
            "jobIds": [
              "labor-preview-daily"
            ],
            "personId": "labor-preview-suda",
            "personIds": [
              "labor-preview-suda"
            ],
            "settlementGroupId": null,
            "settlementRoute": "individual",
            "paymentState": "not_applicable",
            "amountSatang": 35000,
            "dueSatang": 0,
            "remainingSatang": 0
          },
          {
            "id": "group-receipt:labor-preview-group-receipt",
            "eventType": "group_receipt",
            "effectiveDate": "2026-08-02",
            "recordedAt": "2026-08-02T08:02:01.000Z",
            "label": "รับเงินชุดงาน · กรอกถุงเพาะชำ",
            "detail": "พี่สุรับแทนชุดงาน",
            "jobId": "labor-preview-group-piece",
            "jobIds": [
              "labor-preview-group-piece"
            ],
            "personId": null,
            "personIds": [],
            "settlementGroupId": "labor-preview-group-piece-settlement",
            "settlementRoute": "group",
            "paymentState": "not_applicable",
            "amountSatang": 412500,
            "dueSatang": 0,
            "remainingSatang": 0
          }
        ],
        "workCount": 1,
        "workDueSatang": 35000,
        "individualPaymentSatang": 35000,
        "groupReceiptSatang": 412500,
        "advanceIssuedSatang": 0,
        "advanceRecoveredSatang": 0,
        "contractProgressCount": 0,
        "contractCompletionCount": 0,
        "contractDeadlineCount": 0
      },
      {
        "date": "2026-08-03",
        "events": [],
        "workCount": 0,
        "workDueSatang": 0,
        "individualPaymentSatang": 0,
        "groupReceiptSatang": 0,
        "advanceIssuedSatang": 0,
        "advanceRecoveredSatang": 0,
        "contractProgressCount": 0,
        "contractCompletionCount": 0,
        "contractDeadlineCount": 0
      },
      {
        "date": "2026-08-04",
        "events": [],
        "workCount": 0,
        "workDueSatang": 0,
        "individualPaymentSatang": 0,
        "groupReceiptSatang": 0,
        "advanceIssuedSatang": 0,
        "advanceRecoveredSatang": 0,
        "contractProgressCount": 0,
        "contractCompletionCount": 0,
        "contractDeadlineCount": 0
      },
      {
        "date": "2026-08-05",
        "events": [],
        "workCount": 0,
        "workDueSatang": 0,
        "individualPaymentSatang": 0,
        "groupReceiptSatang": 0,
        "advanceIssuedSatang": 0,
        "advanceRecoveredSatang": 0,
        "contractProgressCount": 0,
        "contractCompletionCount": 0,
        "contractDeadlineCount": 0
      },
      {
        "date": "2026-08-06",
        "events": [],
        "workCount": 0,
        "workDueSatang": 0,
        "individualPaymentSatang": 0,
        "groupReceiptSatang": 0,
        "advanceIssuedSatang": 0,
        "advanceRecoveredSatang": 0,
        "contractProgressCount": 0,
        "contractCompletionCount": 0,
        "contractDeadlineCount": 0
      },
      {
        "date": "2026-08-07",
        "events": [],
        "workCount": 0,
        "workDueSatang": 0,
        "individualPaymentSatang": 0,
        "groupReceiptSatang": 0,
        "advanceIssuedSatang": 0,
        "advanceRecoveredSatang": 0,
        "contractProgressCount": 0,
        "contractCompletionCount": 0,
        "contractDeadlineCount": 0
      },
      {
        "date": "2026-08-08",
        "events": [],
        "workCount": 0,
        "workDueSatang": 0,
        "individualPaymentSatang": 0,
        "groupReceiptSatang": 0,
        "advanceIssuedSatang": 0,
        "advanceRecoveredSatang": 0,
        "contractProgressCount": 0,
        "contractCompletionCount": 0,
        "contractDeadlineCount": 0
      },
      {
        "date": "2026-08-09",
        "events": [],
        "workCount": 0,
        "workDueSatang": 0,
        "individualPaymentSatang": 0,
        "groupReceiptSatang": 0,
        "advanceIssuedSatang": 0,
        "advanceRecoveredSatang": 0,
        "contractProgressCount": 0,
        "contractCompletionCount": 0,
        "contractDeadlineCount": 0
      },
      {
        "date": "2026-08-10",
        "events": [],
        "workCount": 0,
        "workDueSatang": 0,
        "individualPaymentSatang": 0,
        "groupReceiptSatang": 0,
        "advanceIssuedSatang": 0,
        "advanceRecoveredSatang": 0,
        "contractProgressCount": 0,
        "contractCompletionCount": 0,
        "contractDeadlineCount": 0
      },
      {
        "date": "2026-08-11",
        "events": [],
        "workCount": 0,
        "workDueSatang": 0,
        "individualPaymentSatang": 0,
        "groupReceiptSatang": 0,
        "advanceIssuedSatang": 0,
        "advanceRecoveredSatang": 0,
        "contractProgressCount": 0,
        "contractCompletionCount": 0,
        "contractDeadlineCount": 0
      },
      {
        "date": "2026-08-12",
        "events": [],
        "workCount": 0,
        "workDueSatang": 0,
        "individualPaymentSatang": 0,
        "groupReceiptSatang": 0,
        "advanceIssuedSatang": 0,
        "advanceRecoveredSatang": 0,
        "contractProgressCount": 0,
        "contractCompletionCount": 0,
        "contractDeadlineCount": 0
      },
      {
        "date": "2026-08-13",
        "events": [],
        "workCount": 0,
        "workDueSatang": 0,
        "individualPaymentSatang": 0,
        "groupReceiptSatang": 0,
        "advanceIssuedSatang": 0,
        "advanceRecoveredSatang": 0,
        "contractProgressCount": 0,
        "contractCompletionCount": 0,
        "contractDeadlineCount": 0
      },
      {
        "date": "2026-08-14",
        "events": [],
        "workCount": 0,
        "workDueSatang": 0,
        "individualPaymentSatang": 0,
        "groupReceiptSatang": 0,
        "advanceIssuedSatang": 0,
        "advanceRecoveredSatang": 0,
        "contractProgressCount": 0,
        "contractCompletionCount": 0,
        "contractDeadlineCount": 0
      },
      {
        "date": "2026-08-15",
        "events": [],
        "workCount": 0,
        "workDueSatang": 0,
        "individualPaymentSatang": 0,
        "groupReceiptSatang": 0,
        "advanceIssuedSatang": 0,
        "advanceRecoveredSatang": 0,
        "contractProgressCount": 0,
        "contractCompletionCount": 0,
        "contractDeadlineCount": 0
      },
      {
        "date": "2026-08-16",
        "events": [],
        "workCount": 0,
        "workDueSatang": 0,
        "individualPaymentSatang": 0,
        "groupReceiptSatang": 0,
        "advanceIssuedSatang": 0,
        "advanceRecoveredSatang": 0,
        "contractProgressCount": 0,
        "contractCompletionCount": 0,
        "contractDeadlineCount": 0
      },
      {
        "date": "2026-08-17",
        "events": [],
        "workCount": 0,
        "workDueSatang": 0,
        "individualPaymentSatang": 0,
        "groupReceiptSatang": 0,
        "advanceIssuedSatang": 0,
        "advanceRecoveredSatang": 0,
        "contractProgressCount": 0,
        "contractCompletionCount": 0,
        "contractDeadlineCount": 0
      },
      {
        "date": "2026-08-18",
        "events": [],
        "workCount": 0,
        "workDueSatang": 0,
        "individualPaymentSatang": 0,
        "groupReceiptSatang": 0,
        "advanceIssuedSatang": 0,
        "advanceRecoveredSatang": 0,
        "contractProgressCount": 0,
        "contractCompletionCount": 0,
        "contractDeadlineCount": 0
      },
      {
        "date": "2026-08-19",
        "events": [],
        "workCount": 0,
        "workDueSatang": 0,
        "individualPaymentSatang": 0,
        "groupReceiptSatang": 0,
        "advanceIssuedSatang": 0,
        "advanceRecoveredSatang": 0,
        "contractProgressCount": 0,
        "contractCompletionCount": 0,
        "contractDeadlineCount": 0
      },
      {
        "date": "2026-08-20",
        "events": [],
        "workCount": 0,
        "workDueSatang": 0,
        "individualPaymentSatang": 0,
        "groupReceiptSatang": 0,
        "advanceIssuedSatang": 0,
        "advanceRecoveredSatang": 0,
        "contractProgressCount": 0,
        "contractCompletionCount": 0,
        "contractDeadlineCount": 0
      },
      {
        "date": "2026-08-21",
        "events": [],
        "workCount": 0,
        "workDueSatang": 0,
        "individualPaymentSatang": 0,
        "groupReceiptSatang": 0,
        "advanceIssuedSatang": 0,
        "advanceRecoveredSatang": 0,
        "contractProgressCount": 0,
        "contractCompletionCount": 0,
        "contractDeadlineCount": 0
      },
      {
        "date": "2026-08-22",
        "events": [],
        "workCount": 0,
        "workDueSatang": 0,
        "individualPaymentSatang": 0,
        "groupReceiptSatang": 0,
        "advanceIssuedSatang": 0,
        "advanceRecoveredSatang": 0,
        "contractProgressCount": 0,
        "contractCompletionCount": 0,
        "contractDeadlineCount": 0
      },
      {
        "date": "2026-08-23",
        "events": [],
        "workCount": 0,
        "workDueSatang": 0,
        "individualPaymentSatang": 0,
        "groupReceiptSatang": 0,
        "advanceIssuedSatang": 0,
        "advanceRecoveredSatang": 0,
        "contractProgressCount": 0,
        "contractCompletionCount": 0,
        "contractDeadlineCount": 0
      },
      {
        "date": "2026-08-24",
        "events": [],
        "workCount": 0,
        "workDueSatang": 0,
        "individualPaymentSatang": 0,
        "groupReceiptSatang": 0,
        "advanceIssuedSatang": 0,
        "advanceRecoveredSatang": 0,
        "contractProgressCount": 0,
        "contractCompletionCount": 0,
        "contractDeadlineCount": 0
      },
      {
        "date": "2026-08-25",
        "events": [],
        "workCount": 0,
        "workDueSatang": 0,
        "individualPaymentSatang": 0,
        "groupReceiptSatang": 0,
        "advanceIssuedSatang": 0,
        "advanceRecoveredSatang": 0,
        "contractProgressCount": 0,
        "contractCompletionCount": 0,
        "contractDeadlineCount": 0
      },
      {
        "date": "2026-08-26",
        "events": [],
        "workCount": 0,
        "workDueSatang": 0,
        "individualPaymentSatang": 0,
        "groupReceiptSatang": 0,
        "advanceIssuedSatang": 0,
        "advanceRecoveredSatang": 0,
        "contractProgressCount": 0,
        "contractCompletionCount": 0,
        "contractDeadlineCount": 0
      },
      {
        "date": "2026-08-27",
        "events": [],
        "workCount": 0,
        "workDueSatang": 0,
        "individualPaymentSatang": 0,
        "groupReceiptSatang": 0,
        "advanceIssuedSatang": 0,
        "advanceRecoveredSatang": 0,
        "contractProgressCount": 0,
        "contractCompletionCount": 0,
        "contractDeadlineCount": 0
      },
      {
        "date": "2026-08-28",
        "events": [],
        "workCount": 0,
        "workDueSatang": 0,
        "individualPaymentSatang": 0,
        "groupReceiptSatang": 0,
        "advanceIssuedSatang": 0,
        "advanceRecoveredSatang": 0,
        "contractProgressCount": 0,
        "contractCompletionCount": 0,
        "contractDeadlineCount": 0
      },
      {
        "date": "2026-08-29",
        "events": [],
        "workCount": 0,
        "workDueSatang": 0,
        "individualPaymentSatang": 0,
        "groupReceiptSatang": 0,
        "advanceIssuedSatang": 0,
        "advanceRecoveredSatang": 0,
        "contractProgressCount": 0,
        "contractCompletionCount": 0,
        "contractDeadlineCount": 0
      },
      {
        "date": "2026-08-30",
        "events": [],
        "workCount": 0,
        "workDueSatang": 0,
        "individualPaymentSatang": 0,
        "groupReceiptSatang": 0,
        "advanceIssuedSatang": 0,
        "advanceRecoveredSatang": 0,
        "contractProgressCount": 0,
        "contractCompletionCount": 0,
        "contractDeadlineCount": 0
      },
      {
        "date": "2026-08-31",
        "events": [],
        "workCount": 0,
        "workDueSatang": 0,
        "individualPaymentSatang": 0,
        "groupReceiptSatang": 0,
        "advanceIssuedSatang": 0,
        "advanceRecoveredSatang": 0,
        "contractProgressCount": 0,
        "contractCompletionCount": 0,
        "contractDeadlineCount": 0
      }
    ]
  },
  "history": {
    "events": [
      {
        "id": "group-receipt:labor-preview-group-receipt",
        "eventType": "group_receipt",
        "effectiveDate": "2026-08-02",
        "recordedAt": "2026-08-02T08:02:01.000Z",
        "label": "รับเงินชุดงาน · กรอกถุงเพาะชำ",
        "detail": "พี่สุรับแทนชุดงาน",
        "jobId": "labor-preview-group-piece",
        "jobIds": [
          "labor-preview-group-piece"
        ],
        "personId": null,
        "personIds": [],
        "settlementGroupId": "labor-preview-group-piece-settlement",
        "settlementRoute": "group",
        "paymentState": "not_applicable",
        "amountSatang": 412500,
        "dueSatang": 0,
        "remainingSatang": 0
      },
      {
        "id": "payment:labor-preview-daily-payment",
        "eventType": "individual_payment",
        "effectiveDate": "2026-08-02",
        "recordedAt": "2026-08-02T08:01:01.000Z",
        "label": "จ่ายค่าแรง · พี่สุ",
        "detail": "ตัดหญ้ารอบบ้าน",
        "jobId": "labor-preview-daily",
        "jobIds": [
          "labor-preview-daily"
        ],
        "personId": "labor-preview-suda",
        "personIds": [
          "labor-preview-suda"
        ],
        "settlementGroupId": null,
        "settlementRoute": "individual",
        "paymentState": "not_applicable",
        "amountSatang": 35000,
        "dueSatang": 0,
        "remainingSatang": 0
      },
      {
        "id": "work:labor-preview-daily",
        "eventType": "work",
        "effectiveDate": "2026-08-02",
        "recordedAt": "2026-08-02T08:01:00.000Z",
        "label": "ตัดหญ้ารอบบ้าน",
        "detail": "พี่สุ",
        "jobId": "labor-preview-daily",
        "jobIds": [
          "labor-preview-daily"
        ],
        "personId": null,
        "personIds": [
          "labor-preview-suda"
        ],
        "settlementGroupId": null,
        "settlementRoute": "individual",
        "paymentState": "paid",
        "amountSatang": 0,
        "dueSatang": 35000,
        "remainingSatang": 0
      },
      {
        "id": "advance:labor-preview-chon-advance",
        "eventType": "advance",
        "effectiveDate": "2026-08-01",
        "recordedAt": "2026-08-02T08:03:00.000Z",
        "label": "เงินเบิก · น้าชล",
        "detail": "ตัวอย่างเงินเบิก",
        "jobId": null,
        "jobIds": [],
        "personId": "labor-preview-chon",
        "personIds": [
          "labor-preview-chon"
        ],
        "settlementGroupId": null,
        "settlementRoute": null,
        "paymentState": "not_applicable",
        "amountSatang": 100000,
        "dueSatang": 0,
        "remainingSatang": 0
      },
      {
        "id": "work:labor-preview-group-piece",
        "eventType": "work",
        "effectiveDate": "2026-08-01",
        "recordedAt": "2026-08-02T08:02:00.000Z",
        "label": "กรอกถุงเพาะชำ",
        "detail": "พี่สุ · พี่พวง",
        "jobId": "labor-preview-group-piece",
        "jobIds": [
          "labor-preview-group-piece"
        ],
        "personId": null,
        "personIds": [
          "labor-preview-suda",
          "labor-preview-phuang"
        ],
        "settlementGroupId": "labor-preview-group-piece-settlement",
        "settlementRoute": "group",
        "paymentState": "paid",
        "amountSatang": 0,
        "dueSatang": 412500,
        "remainingSatang": 0
      }
    ],
    "total": 5
  },
  "jobs": {
    "labor-preview-daily": {
      "id": "labor-preview-daily",
      "title": "ตัดหญ้ารอบบ้าน",
      "kind": "normal",
      "workDate": "2026-08-02",
      "note": "",
      "createdAt": "2026-08-02T08:01:00.000Z",
      "settlementRoute": "individual",
      "paymentState": "paid",
      "dueSatang": 35000,
      "cashPaidSatang": 35000,
      "advanceRecoveredSatang": 0,
      "remainingSatang": 0,
      "participants": [
        {
          "personId": "labor-preview-suda",
          "displayName": "พี่สุ",
          "payType": "daily"
        }
      ],
      "settlementGroup": null,
      "contract": null,
      "workBasisSnapshots": [
        {
          "id": "labor-preview-daily-basis-1",
          "jobId": "labor-preview-daily",
          "settlementRoute": "individual",
          "basisKind": "daily",
          "stage": "recorded",
          "personId": "labor-preview-suda",
          "rateSatang": 35000,
          "quantityMilli": 1000,
          "durationMinutes": null,
          "unitLabel": "วัน",
          "totalSatang": 35000,
          "note": "",
          "createdAt": "2026-08-02T08:01:00.000Z"
        }
      ],
      "events": [
        {
          "id": "work:labor-preview-daily",
          "eventType": "work",
          "effectiveDate": "2026-08-02",
          "recordedAt": "2026-08-02T08:01:00.000Z",
          "label": "ตัดหญ้ารอบบ้าน",
          "detail": "พี่สุ",
          "jobId": "labor-preview-daily",
          "jobIds": [
            "labor-preview-daily"
          ],
          "personId": null,
          "personIds": [
            "labor-preview-suda"
          ],
          "settlementGroupId": null,
          "settlementRoute": "individual",
          "paymentState": "paid",
          "amountSatang": 0,
          "dueSatang": 35000,
          "remainingSatang": 0
        },
        {
          "id": "payment:labor-preview-daily-payment",
          "eventType": "individual_payment",
          "effectiveDate": "2026-08-02",
          "recordedAt": "2026-08-02T08:01:01.000Z",
          "label": "จ่ายค่าแรง · พี่สุ",
          "detail": "ตัดหญ้ารอบบ้าน",
          "jobId": "labor-preview-daily",
          "jobIds": [
            "labor-preview-daily"
          ],
          "personId": "labor-preview-suda",
          "personIds": [
            "labor-preview-suda"
          ],
          "settlementGroupId": null,
          "settlementRoute": "individual",
          "paymentState": "not_applicable",
          "amountSatang": 35000,
          "dueSatang": 0,
          "remainingSatang": 0
        }
      ]
    },
    "labor-preview-group-piece": {
      "id": "labor-preview-group-piece",
      "title": "กรอกถุงเพาะชำ",
      "kind": "normal",
      "workDate": "2026-08-01",
      "note": "",
      "createdAt": "2026-08-02T08:02:00.000Z",
      "settlementRoute": "group",
      "paymentState": "paid",
      "dueSatang": 412500,
      "cashPaidSatang": 412500,
      "advanceRecoveredSatang": 0,
      "remainingSatang": 0,
      "participants": [
        {
          "personId": "labor-preview-suda",
          "displayName": "พี่สุ",
          "payType": "piece"
        },
        {
          "personId": "labor-preview-phuang",
          "displayName": "พี่พวง",
          "payType": "piece"
        }
      ],
      "settlementGroup": {
        "id": "labor-preview-group-piece-settlement",
        "jobId": "labor-preview-group-piece",
        "originalDueSatang": 412500,
        "paidSatang": 412500,
        "remainingSatang": 0,
        "status": "settled",
        "collectorPersonId": null,
        "collectorLabel": "พี่สุรับแทนชุดงาน",
        "memberPersonIds": [
          "labor-preview-suda",
          "labor-preview-phuang"
        ],
        "receipts": [
          {
            "id": "labor-preview-group-receipt",
            "settlementGroupId": "labor-preview-group-piece-settlement",
            "receiptDate": "2026-08-02",
            "amountSatang": 412500,
            "method": "cash",
            "note": "",
            "currentRevision": 1,
            "status": "posted"
          }
        ]
      },
      "contract": null,
      "workBasisSnapshots": [
        {
          "id": "labor-preview-group-piece-basis-1",
          "jobId": "labor-preview-group-piece",
          "settlementRoute": "group",
          "basisKind": "piece",
          "stage": "recorded",
          "personId": null,
          "rateSatang": 100,
          "quantityMilli": 4125000,
          "durationMinutes": null,
          "unitLabel": "ถุง",
          "totalSatang": 412500,
          "note": "",
          "createdAt": "2026-08-02T08:02:00.000Z"
        }
      ],
      "events": [
        {
          "id": "work:labor-preview-group-piece",
          "eventType": "work",
          "effectiveDate": "2026-08-01",
          "recordedAt": "2026-08-02T08:02:00.000Z",
          "label": "กรอกถุงเพาะชำ",
          "detail": "พี่สุ · พี่พวง",
          "jobId": "labor-preview-group-piece",
          "jobIds": [
            "labor-preview-group-piece"
          ],
          "personId": null,
          "personIds": [
            "labor-preview-suda",
            "labor-preview-phuang"
          ],
          "settlementGroupId": "labor-preview-group-piece-settlement",
          "settlementRoute": "group",
          "paymentState": "paid",
          "amountSatang": 0,
          "dueSatang": 412500,
          "remainingSatang": 0
        },
        {
          "id": "group-receipt:labor-preview-group-receipt",
          "eventType": "group_receipt",
          "effectiveDate": "2026-08-02",
          "recordedAt": "2026-08-02T08:02:01.000Z",
          "label": "รับเงินชุดงาน · กรอกถุงเพาะชำ",
          "detail": "พี่สุรับแทนชุดงาน",
          "jobId": "labor-preview-group-piece",
          "jobIds": [
            "labor-preview-group-piece"
          ],
          "personId": null,
          "personIds": [],
          "settlementGroupId": "labor-preview-group-piece-settlement",
          "settlementRoute": "group",
          "paymentState": "not_applicable",
          "amountSatang": 412500,
          "dueSatang": 0,
          "remainingSatang": 0
        }
      ]
    }
  },
  "people": {
    "labor-preview-chon": {
      "person": {
        "id": "labor-preview-chon",
        "displayName": "น้าชล",
        "specialty": "งานรายชั่วโมง",
        "phone": "",
        "note": "",
        "archivedAt": null,
        "dueSatang": 0,
        "paidSatang": 0,
        "remainingSatang": 0,
        "grossEarnedSatang": 0,
        "cashPaidSatang": 0,
        "wageRemainingSatang": 0,
        "advanceIssuedSatang": 100000,
        "advanceRecoveredSatang": 0,
        "advanceRemainingSatang": 100000
      },
      "wagePayables": [],
      "advances": [
        {
          "id": "labor-preview-chon-advance",
          "personId": "labor-preview-chon",
          "advanceDate": "2026-08-01",
          "amountSatang": 100000,
          "recoveredSatang": 0,
          "remainingSatang": 100000,
          "method": "cash",
          "note": "ตัวอย่างเงินเบิก",
          "currentRevision": 1,
          "status": "posted"
        }
      ],
      "advanceDeductions": [],
      "events": [
        {
          "id": "advance:labor-preview-chon-advance",
          "eventType": "advance",
          "effectiveDate": "2026-08-01",
          "recordedAt": "2026-08-02T08:03:00.000Z",
          "label": "เงินเบิก · น้าชล",
          "detail": "ตัวอย่างเงินเบิก",
          "jobId": null,
          "jobIds": [],
          "personId": "labor-preview-chon",
          "personIds": [
            "labor-preview-chon"
          ],
          "settlementGroupId": null,
          "settlementRoute": null,
          "paymentState": "not_applicable",
          "amountSatang": 100000,
          "dueSatang": 0,
          "remainingSatang": 0
        }
      ]
    },
    "labor-preview-phuang": {
      "person": {
        "id": "labor-preview-phuang",
        "displayName": "พี่พวง",
        "specialty": "กรอกถุงเพาะชำ",
        "phone": "",
        "note": "",
        "archivedAt": null,
        "dueSatang": 0,
        "paidSatang": 0,
        "remainingSatang": 0,
        "grossEarnedSatang": 0,
        "cashPaidSatang": 0,
        "wageRemainingSatang": 0,
        "advanceIssuedSatang": 0,
        "advanceRecoveredSatang": 0,
        "advanceRemainingSatang": 0
      },
      "wagePayables": [],
      "advances": [],
      "advanceDeductions": [],
      "events": [
        {
          "id": "work:labor-preview-group-piece",
          "eventType": "work",
          "effectiveDate": "2026-08-01",
          "recordedAt": "2026-08-02T08:02:00.000Z",
          "label": "กรอกถุงเพาะชำ",
          "detail": "พี่สุ · พี่พวง",
          "jobId": "labor-preview-group-piece",
          "jobIds": [
            "labor-preview-group-piece"
          ],
          "personId": null,
          "personIds": [
            "labor-preview-suda",
            "labor-preview-phuang"
          ],
          "settlementGroupId": "labor-preview-group-piece-settlement",
          "settlementRoute": "group",
          "paymentState": "paid",
          "amountSatang": 0,
          "dueSatang": 412500,
          "remainingSatang": 0
        }
      ]
    },
    "labor-preview-suda": {
      "person": {
        "id": "labor-preview-suda",
        "displayName": "พี่สุ",
        "specialty": "งานรายวันและกรอกถุง",
        "phone": "",
        "note": "",
        "archivedAt": null,
        "dueSatang": 35000,
        "paidSatang": 35000,
        "remainingSatang": 0,
        "grossEarnedSatang": 35000,
        "cashPaidSatang": 35000,
        "wageRemainingSatang": 0,
        "advanceIssuedSatang": 0,
        "advanceRecoveredSatang": 0,
        "advanceRemainingSatang": 0
      },
      "wagePayables": [
        {
          "id": "labor-preview-daily-payable-1",
          "jobId": "labor-preview-daily",
          "jobTitle": "ตัดหญ้ารอบบ้าน",
          "workDate": "2026-08-02",
          "personId": "labor-preview-suda",
          "dueSatang": 35000,
          "paidSatang": 35000,
          "recoveredSatang": 0,
          "remainingSatang": 0,
          "kind": "normal"
        }
      ],
      "advances": [],
      "advanceDeductions": [],
      "events": [
        {
          "id": "work:labor-preview-group-piece",
          "eventType": "work",
          "effectiveDate": "2026-08-01",
          "recordedAt": "2026-08-02T08:02:00.000Z",
          "label": "กรอกถุงเพาะชำ",
          "detail": "พี่สุ · พี่พวง",
          "jobId": "labor-preview-group-piece",
          "jobIds": [
            "labor-preview-group-piece"
          ],
          "personId": null,
          "personIds": [
            "labor-preview-suda",
            "labor-preview-phuang"
          ],
          "settlementGroupId": "labor-preview-group-piece-settlement",
          "settlementRoute": "group",
          "paymentState": "paid",
          "amountSatang": 0,
          "dueSatang": 412500,
          "remainingSatang": 0
        },
        {
          "id": "work:labor-preview-daily",
          "eventType": "work",
          "effectiveDate": "2026-08-02",
          "recordedAt": "2026-08-02T08:01:00.000Z",
          "label": "ตัดหญ้ารอบบ้าน",
          "detail": "พี่สุ",
          "jobId": "labor-preview-daily",
          "jobIds": [
            "labor-preview-daily"
          ],
          "personId": null,
          "personIds": [
            "labor-preview-suda"
          ],
          "settlementGroupId": null,
          "settlementRoute": "individual",
          "paymentState": "paid",
          "amountSatang": 0,
          "dueSatang": 35000,
          "remainingSatang": 0
        },
        {
          "id": "payment:labor-preview-daily-payment",
          "eventType": "individual_payment",
          "effectiveDate": "2026-08-02",
          "recordedAt": "2026-08-02T08:01:01.000Z",
          "label": "จ่ายค่าแรง · พี่สุ",
          "detail": "ตัดหญ้ารอบบ้าน",
          "jobId": "labor-preview-daily",
          "jobIds": [
            "labor-preview-daily"
          ],
          "personId": "labor-preview-suda",
          "personIds": [
            "labor-preview-suda"
          ],
          "settlementGroupId": null,
          "settlementRoute": "individual",
          "paymentState": "not_applicable",
          "amountSatang": 35000,
          "dueSatang": 0,
          "remainingSatang": 0
        }
      ]
    }
  }
};
