import type { LaborPreviewAdapter } from './preview';
import type { LaborCalendarDaySummary, LaborCalendarRangeInput, LaborHistoryInput, LaborMvpReadModel, LaborProjectionEvent } from './types';
import { LABOR_PREVIEW_WEB_PROJECTIONS, LABOR_PREVIEW_WEB_READ_MODEL } from './preview.web.fixture';

const matches = (event: LaborProjectionEvent, input: LaborCalendarRangeInput): boolean => {
  if (input.personId && event.personId !== input.personId && !event.personIds.includes(input.personId)) return false;
  if (input.eventTypes?.length && !input.eventTypes.includes(event.eventType)) return false;
  if (input.paymentState && event.paymentState !== input.paymentState) return false;
  if (input.settlementRoute && event.settlementRoute !== input.settlementRoute) return false;
  const keyword = input.keyword?.trim().toLocaleLowerCase('th-TH');
  return !keyword || `${event.label} ${event.detail}`.toLocaleLowerCase('th-TH').includes(keyword);
};

const calendar = (input: LaborCalendarRangeInput) => ({
  startDate: input.startDate,
  endDate: input.endDate,
  days: LABOR_PREVIEW_WEB_PROJECTIONS.calendar.days
    .filter((day) => day.date >= input.startDate && day.date <= input.endDate)
    .map((day) => ({ ...day, events: day.events.filter((event) => matches(event, input)) })),
});

const history = (input: LaborHistoryInput) => {
  const events = LABOR_PREVIEW_WEB_PROJECTIONS.history.events.filter((event) => event.effectiveDate >= input.startDate && event.effectiveDate <= input.endDate && matches(event, input));
  return { events: input.limit ? events.slice(0, input.limit) : events, total: events.length };
};

/**
 * Expo SQLite's WASM bundle is not available in this repository's web export.
 * This immutable fixture is generated by scripts/generate-labor-preview-web-fixture.ts
 * from the same migration + repository command sequence as native preview.
 */
export const createWebLaborPreviewAdapter = (): LaborPreviewAdapter => ({
  mode: 'proof',
  platform: 'web-preview',
  label: 'ข้อมูลทดสอบ',
  fixtureVersion: 'labor-preview-v1',
  getReadModel: async () => structuredClone(LABOR_PREVIEW_WEB_READ_MODEL),
  getTodaySummary: async (date = '2026-08-02') => date === LABOR_PREVIEW_WEB_PROJECTIONS.today.date
    ? structuredClone(LABOR_PREVIEW_WEB_PROJECTIONS.today)
    : { date, day: { date, events: [], workCount: 0, workDueSatang: 0, individualPaymentSatang: 0, groupReceiptSatang: 0, advanceIssuedSatang: 0, advanceRecoveredSatang: 0, contractProgressCount: 0, contractCompletionCount: 0, contractDeadlineCount: 0 }, unpaidPeople: [], advanceAttentionPeople: [] },
  getCalendarRange: async (input) => structuredClone(calendar(input)),
  getHistory: async (input) => structuredClone(history(input)),
  getJobDetail: async (jobId) => structuredClone(LABOR_PREVIEW_WEB_PROJECTIONS.jobs[jobId] ?? null),
  getPersonDetail: async (personId) => structuredClone(LABOR_PREVIEW_WEB_PROJECTIONS.people[personId] ?? null),
  workers: {
    list: async ({ includeArchived = false } = {}) => structuredClone(LABOR_PREVIEW_WEB_READ_MODEL.people
      .filter((person) => includeArchived || !person.archivedAt)
      .map(({ id, displayName, specialty, phone, note, archivedAt }) => ({ id, displayName, specialty, phone, note, archivedAt }))),
    create: readonlyPreview,
    update: readonlyPreview,
    archive: readonlyPreview,
  },
  commands: {
    createNormalWork: readonlyPreview,
    createGroupPieceWork: readonlyPreview,
    recordLaborWorkItems: readonlyPreview,
    postLaborPaymentSession: readonlyPreview,
    createLaborContract: readonlyPreview,
    createLaborSettlementGroup: readonlyPreview,
    addLaborContractProgress: readonlyPreview,
    completeLaborContractWork: readonlyPreview,
    postLaborPayment: readonlyPreview,
    postLaborSettlementGroupReceipt: readonlyPreview,
    createLaborWorkerAdvance: readonlyPreview,
    applyLaborAdvanceDeduction: readonlyPreview,
    editLaborPayment: readonlyPreview,
    editLaborSettlementGroupReceipt: readonlyPreview,
    editLaborWorkerAdvance: readonlyPreview,
  },
});

const emptyModel = (): LaborMvpReadModel => ({
  people: [], payables: [], payments: [], timeline: [], contracts: [], legacySources: [], legacyBalances: [], settlementGroups: [], workBasisSnapshots: [], advances: [], advanceDeductions: [],
});

const emptyDay = (date: string): LaborCalendarDaySummary => ({
  date, events: [], workCount: 0, workDueSatang: 0, individualPaymentSatang: 0, groupReceiptSatang: 0, advanceIssuedSatang: 0, advanceRecoveredSatang: 0, contractProgressCount: 0, contractCompletionCount: 0, contractDeadlineCount: 0,
});

const daysBetween = (startDate: string, endDate: string): LaborCalendarDaySummary[] => {
  const days: LaborCalendarDaySummary[] = [];
  const cursor = new Date(`${startDate}T12:00:00`);
  const end = new Date(`${endDate}T12:00:00`);
  while (cursor <= end) {
    days.push(emptyDay(cursor.toISOString().slice(0, 10)));
    cursor.setDate(cursor.getDate() + 1);
  }
  return days;
};

/** Web has no SQLite bundle here, so product boot is honestly read-only and empty. */
export const createWebLaborNotebookAdapter = (): LaborPreviewAdapter => ({
  mode: 'notebook',
  platform: 'web-notebook',
  getReadModel: async () => emptyModel(),
  getTodaySummary: async (date = new Date().toISOString().slice(0, 10)) => ({ date, day: emptyDay(date), unpaidPeople: [], advanceAttentionPeople: [] }),
  getCalendarRange: async ({ startDate, endDate }) => ({ startDate, endDate, days: daysBetween(startDate, endDate) }),
  getHistory: async () => ({ events: [], total: 0 }),
  getJobDetail: async () => null,
  getPersonDetail: async () => null,
  workers: { list: async () => [], create: readonlyNotebook, update: readonlyNotebook, archive: readonlyNotebook },
  commands: {
    createNormalWork: readonlyNotebook, createGroupPieceWork: readonlyNotebook, recordLaborWorkItems: readonlyNotebook, postLaborPaymentSession: readonlyNotebook, createLaborContract: readonlyNotebook, createLaborSettlementGroup: readonlyNotebook,
    addLaborContractProgress: readonlyNotebook, completeLaborContractWork: readonlyNotebook, postLaborPayment: readonlyNotebook, postLaborSettlementGroupReceipt: readonlyNotebook,
    createLaborWorkerAdvance: readonlyNotebook, applyLaborAdvanceDeduction: readonlyNotebook, editLaborPayment: readonlyNotebook, editLaborSettlementGroupReceipt: readonlyNotebook, editLaborWorkerAdvance: readonlyNotebook,
  },
});

const readonlyPreview = async (): Promise<never> => {
  throw new Error('ข้อมูลทดสอบบนเว็บเป็นโหมดอ่านอย่างเดียว');
};

const readonlyNotebook = async (): Promise<never> => {
  throw new Error('การบันทึกจากเว็บยังไม่รองรับ กรุณาเปิดแอปบนอุปกรณ์เพื่อบันทึกข้อมูล');
};
