import type { LaborPreviewAdapter } from './preview';
import { LABOR_PREVIEW_WEB_READ_MODEL } from './preview.web.fixture';

/**
 * Expo SQLite's WASM bundle is not available in this repository's web export.
 * This immutable fixture is generated by scripts/generate-labor-preview-web-fixture.ts
 * from the same migration + repository command sequence as native preview.
 */
export const createWebLaborPreviewAdapter = (): LaborPreviewAdapter => ({
  platform: 'web-preview',
  label: 'ตัวอย่าง Labor Preview · ข้อมูลจาก Labor ledger',
  fixtureVersion: 'labor-preview-v1',
  getReadModel: async () => structuredClone(LABOR_PREVIEW_WEB_READ_MODEL),
});
