import { mkdtemp, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { DatabaseSync, type SQLInputValue } from 'node:sqlite';

import type { SqlExecutor } from '../src/data/migrations';
import { runMigrations } from '../src/data/migrations';
import { createLaborPreviewAdapter } from '../src/features/labor-mvp/preview';
import { getLaborCalendarRange, getLaborHistory, getLaborJobDetail, getLaborPersonDetail, getLaborTodaySummary } from '../src/features/labor-mvp/repository';

class NodeSqliteExecutor implements SqlExecutor {
  constructor(private readonly database: DatabaseSync) {}
  async execAsync(sql: string): Promise<void> { this.database.exec(sql); }
  async getAllAsync<T>(sql: string, params: unknown[] = []): Promise<T[]> { return this.database.prepare(sql).all(...(params as SQLInputValue[])) as T[]; }
  async runAsync(sql: string, params: unknown[] = []): Promise<void> { this.database.prepare(sql).run(...(params as SQLInputValue[])); }
}

const main = async (): Promise<void> => {
  const directory = await mkdtemp(join(tmpdir(), 'takai-labor-preview-'));
  const databasePath = join(directory, 'preview.db');
  let connection: DatabaseSync | null = null;
  try {
    connection = new DatabaseSync(databasePath);
    const db = new NodeSqliteExecutor(connection);
    await runMigrations(db);
    const adapter = await createLaborPreviewAdapter(db, 'native-preview');
    const model = await adapter.getReadModel();
    const startDate = '2026-08-01';
    const endDate = '2026-08-31';
    const jobs = await Promise.all(model.workBasisSnapshots.map((snapshot) => snapshot.jobId).filter((jobId, index, ids) => ids.indexOf(jobId) === index).map(async (jobId) => [jobId, await getLaborJobDetail(db, jobId)] as const));
    const people = await Promise.all(model.people.map(async (person) => [person.id, await getLaborPersonDetail(db, person.id)] as const));
    const projections = {
      today: await getLaborTodaySummary(db, '2026-08-02'),
      calendar: await getLaborCalendarRange(db, { startDate, endDate }),
      history: await getLaborHistory(db, { startDate, endDate }),
      jobs: Object.fromEntries(jobs),
      people: Object.fromEntries(people),
    };
    const output = `import type { LaborMvpReadModel, LaborPreviewWebProjections } from './types';\n\n// Generated by scripts/generate-labor-preview-web-fixture.ts. Do not hand-edit.\nexport const LABOR_PREVIEW_WEB_READ_MODEL: LaborMvpReadModel = ${JSON.stringify(model, null, 2)};\n\nexport const LABOR_PREVIEW_WEB_PROJECTIONS: LaborPreviewWebProjections = ${JSON.stringify(projections, null, 2)};\n`;
    await writeFile(resolve(process.cwd(), 'src/features/labor-mvp/preview.web.fixture.ts'), output);
    console.log('LABOR_PREVIEW_WEB_FIXTURE_GENERATED: src/features/labor-mvp/preview.web.fixture.ts');
  } finally {
    connection?.close();
    await rm(directory, { recursive: true, force: true });
  }
};

main().catch((error: unknown) => { console.error(error); process.exit(1); });
