import { mkdtemp, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { DatabaseSync, type SQLInputValue } from 'node:sqlite';
import type { SqlExecutor } from '../src/data/migrations';
import { runMigrations } from '../src/data/migrations';
import { buildLaborV2PreviewFixture } from '../src/features/labor-mvp/previewV2';

class NodeSqliteExecutor implements SqlExecutor { constructor(private readonly database: DatabaseSync) {} async execAsync(sql: string): Promise<void> { this.database.exec(sql); } async getAllAsync<T>(sql: string, params: unknown[] = []): Promise<T[]> { return this.database.prepare(sql).all(...(params as SQLInputValue[])) as T[]; } async runAsync(sql: string, params: unknown[] = []): Promise<void> { this.database.prepare(sql).run(...(params as SQLInputValue[])); } }
const main = async (): Promise<void> => { const directory = await mkdtemp(join(tmpdir(), 'takai-labor-v2-preview-')); let connection: DatabaseSync | null = null; try { connection = new DatabaseSync(join(directory, 'preview.db')); const db = new NodeSqliteExecutor(connection); await runMigrations(db); const fixture = await buildLaborV2PreviewFixture(db); const output = `import type { LaborV2PreviewFixture } from './previewV2';\n\n// Generated by scripts/generate-labor-v2-preview-web-fixture.ts. Do not hand-edit.\nexport const LABOR_V2_PREVIEW_WEB_FIXTURE: LaborV2PreviewFixture = ${JSON.stringify(fixture, null, 2)};\n`; await writeFile(resolve(process.cwd(), 'src/features/labor-mvp/previewV2.web.fixture.ts'), output); console.log('LABOR_V2_PREVIEW_WEB_FIXTURE_GENERATED: src/features/labor-mvp/previewV2.web.fixture.ts'); } finally { connection?.close(); await rm(directory, { recursive: true, force: true }); } };
main().catch((error: unknown) => { console.error(error); process.exit(1); });
