import assert from 'node:assert/strict';
import { DatabaseSync, type SQLInputValue } from 'node:sqlite';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import type { SqlExecutor } from '../src/data/migrations';
import { runMigrations } from '../src/data/migrations';
import { createLaborWorker } from '../src/features/labor-mvp/repository';
import { createWebLaborV2PreviewAdapter } from '../src/features/labor-mvp/previewV2.web';
import { createLaborV2PersonAdvance, finalizeLaborContractBatchV2, getLaborV2MoneyHistory, getLaborV2PaymentBatchDraft, getPersonDetailV2, postLaborV2PaymentSession, recordLaborDayV2, startLaborContractBatchV2 } from '../src/features/labor-mvp/repositoryV2';
import { createLaborV2NotebookAdapter } from '../src/features/labor-mvp/previewV2Adapter';

class NodeSqliteExecutor implements SqlExecutor { constructor(private readonly database: DatabaseSync) {} async execAsync(sql: string): Promise<void> { this.database.exec(sql); } async getAllAsync<T>(sql: string, params: unknown[] = []): Promise<T[]> { return this.database.prepare(sql).all(...(params as SQLInputValue[])) as T[]; } async runAsync(sql: string, params: unknown[] = []): Promise<void> { this.database.prepare(sql).run(...(params as SQLInputValue[])); } }

const main = async (): Promise<void> => { const directory = await mkdtemp(join(tmpdir(), 'takai-payment-read-seams-')); let connection: DatabaseSync | null = null; try {
  connection = new DatabaseSync(join(directory, 'takai.db')); const db = new NodeSqliteExecutor(connection); await runMigrations(db);
  const su = await createLaborWorker(db, { id: 'su', displayName: 'สุ' }); const phuang = await createLaborWorker(db, { id: 'phuang', displayName: 'พวง' }); const advanceOnly = await createLaborWorker(db, { id: 'advance-only', displayName: 'มาลี' });
  await recordLaborDayV2(db, { workDate: '2026-09-01', tasks: [{ id: 'su-task', title: 'ใส่ปุ๋ย', assigneePersonIds: [su] }], daily: [{ id: 'su-day', personId: su, rateSatang: 35_000, quantityMilli: 1000, taskIds: ['su-task'] }] });
  const contract = await startLaborContractBatchV2(db, { id: 'bags', title: 'กรอกถุง', startsOn: '2026-09-01', memberPersonIds: [su, phuang] }); const contractObligation = await finalizeLaborContractBatchV2(db, contract, { finalizedAt: '2026-09-03', finalization: { kind: 'lump_total', finalTotalSatang: 120_000 } });
  const advance = await createLaborV2PersonAdvance(db, { id: 'advance-before-work', personId: advanceOnly, advanceDate: '2026-08-31', amountSatang: 5_000, method: 'cash', note: 'เบิกก่อนเริ่มงาน' });
  await postLaborV2PaymentSession(db, { id: 'su-partial', paymentDate: '2026-09-02', settlements: [{ obligationId: 'obligation:daily:su-day', wageSatang: 10_000 }] });
  const adapter = createLaborV2NotebookAdapter(db); const draft = await adapter.getPaymentBatchDraft({ personId: su, selectedObligationIds: ['obligation:daily:su-day', contractObligation, contractObligation, 'already-settled-or-missing'] });
  assert.deepEqual(draft.available.map((item) => item.obligationId), ['obligation:daily:su-day'], 'person payment context presents only that person debt'); assert.deepEqual(draft.available.map((item) => [item.recipientKind, item.personId, item.remainingSatang, item.effectiveDate]), [['person', su, 25_000, '2026-09-01']], 'person draft retains the current remaining balance and business date'); assert.deepEqual(draft.selected.map((item) => [item.obligationId, item.recipientKind, item.personId, item.recipientLabel, item.remainingSatang]), [['obligation:daily:su-day', 'person', su, 'คนทำงาน', 25_000], [contractObligation, 'group', null, 'ชุดรับเงิน', 120_000]], 'selected rows are unique and retain an explicitly selected group obligation without inventing member debt'); assert.deepEqual(draft.unavailableSelectionIds, ['already-settled-or-missing'], 'stale selected IDs reconcile visibly instead of being silently paid');
  const direct = await getLaborV2PaymentBatchDraft(db, { selectedObligationIds: [contractObligation] }); assert.deepEqual(direct.available.find((item) => item.obligationId === contractObligation), direct.selected[0], 'global batch picker and selected row use the same repository-derived obligation fact');
  const detail = await getPersonDetailV2(db, advanceOnly); assert.deepEqual(detail.advances.map((item) => item.id), [advance], 'standalone advance appears in its person detail with no task needed'); assert.ok(detail.events.some((item) => item.entityId === advance && item.action === 'issued'), 'person detail keeps immutable advance history');
  const money = await getLaborV2MoneyHistory(db); assert.deepEqual(money.entries.map((entry) => [entry.kind, entry.id, entry.effectiveDate]), [['payment', 'su-partial', '2026-09-02'], ['advance', advance, '2026-08-31']], 'money history keeps wage cash and standalone advance as distinct dated facts'); assert.ok(money.events.some((item) => item.entityId === advance && item.action === 'issued'), 'money history exposes immutable advance event history'); assert.equal(money.payments.find((item) => item.id === 'su-partial')?.cashPaidSatang, 10_000, 'advance issuance never changes wage cash paid');
  const web = createWebLaborV2PreviewAdapter(); const webDraft = await web.getPaymentBatchDraft({ personId: 'labor-v2-preview-su', selectedObligationIds: ['obligation:hourly:hourly:labor-v2-preview-chon|2026-08-24|12000|'] }); assert.deepEqual(webDraft.available.map((item) => item.personId), ['labor-v2-preview-su'], 'repository-generated proof fixture keeps person picker scoped'); assert.deepEqual(webDraft.selected.map((item) => item.personId), ['labor-v2-preview-chon'], 'rehydrated web draft preserves an explicitly selected external row'); assert.ok((await web.getMoneyHistory()).entries.some((entry) => entry.kind === 'advance' && entry.id === 'labor-v2-preview-advance'), 'generated proof fixture keeps standalone advance visible in money history');
  console.log('LABOR_PAYMENT_BATCH_READ_SEAMS_PASS: V2 batch selection is unique/context-safe and advance history stays distinct across native and generated web adapters');
} finally { connection?.close(); await rm(directory, { recursive: true, force: true }); } };
main().catch((error: unknown) => { console.error(error); process.exit(1); });
