import assert from 'node:assert/strict';
import { DatabaseSync, type SQLInputValue } from 'node:sqlite';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import type { SqlExecutor } from '../src/data/migrations';
import { runMigrations } from '../src/data/migrations';
import { correctLaborV2PaymentSession, createLaborV2PersonAdvance, finalizeLaborContractBatchV2, getLaborV2Calendar, getLaborV2History, getLaborV2MoneyHistory, getLaborV2Person, getLaborV2ReadModel, getLaborV2Today, getLaborV2Unpaid, listLaborV2PersonAdvances, listOpenLaborContractBatchesV2, postLaborV2PaymentSession, recordLaborDayV2, recordLaborContractProgressV2, startLaborContractBatchV2 } from '../src/features/labor-mvp/repositoryV2';
import { createLaborWorker, createLaborWorkerAdvance } from '../src/features/labor-mvp/repository';

class NodeSqliteExecutor implements SqlExecutor { constructor(private readonly database: DatabaseSync) {} async execAsync(sql: string): Promise<void> { this.database.exec(sql); } async getAllAsync<T>(sql: string, params: unknown[] = []): Promise<T[]> { return this.database.prepare(sql).all(...(params as SQLInputValue[])) as T[]; } async runAsync(sql: string, params: unknown[] = []): Promise<void> { this.database.prepare(sql).run(...(params as SQLInputValue[])); } }

const main = async (): Promise<void> => { const directory = await mkdtemp(join(tmpdir(), 'takai-v2-command-')); let connection: DatabaseSync | null = null; try { connection = new DatabaseSync(join(directory, 'takai.db')); const db = new NodeSqliteExecutor(connection); await runMigrations(db); const su = await createLaborWorker(db, { id: 'su', displayName: 'สุ' }); const phuang = await createLaborWorker(db, { id: 'phuang', displayName: 'พวง' }); const chon = await createLaborWorker(db, { id: 'chon', displayName: 'ชล' });
  await recordLaborDayV2(db, { workDate: '2026-08-21', tasks: [{ id: 'shade', title: 'ขึงสแลน', assigneePersonIds: [su] }, { id: 'fert', title: 'ใส่ปุ๋ย', assigneePersonIds: [su] }, { id: 'spray', title: 'พ่นยา', assigneePersonIds: [su] }], daily: [{ id: 'su-day', personId: su, rateSatang: 35_000, quantityMilli: 1000, taskIds: ['shade', 'fert', 'spray'] }] });
  const openContract = await startLaborContractBatchV2(db, { id: 'bags', title: 'กรอกถุง', startsOn: '2026-08-21', memberPersonIds: [su, phuang] });
  assert.deepEqual(await listOpenLaborContractBatchesV2(db), [{ id: 'bags', title: 'กรอกถุง', startsOn: '2026-08-21', memberPersonIds: [su, phuang] }], 'open contract projection exposes the actual batch and named members without an obligation');
  await recordLaborContractProgressV2(db, openContract, { progressDate: '2026-08-22', note: 'เริ่มทำ' });
  let read = await getLaborV2ReadModel(db); assert.equal(read.tasks.length, 3, 'calendar/work truth counts tasks, not money'); assert.deepEqual(read.obligations.map((item) => [item.sourceKind, item.dueSatang]), [['daily', 35_000]], 'open unpriced contract adds no payable'); assert.equal((await db.getAllAsync<{ count: number }>('SELECT count(*) count FROM labor_payables'))[0]!.count, 0, 'V2 commands never fabricate v1 payables');
  const dailyPayment = await postLaborV2PaymentSession(db, { id: 'pay-daily', paymentDate: '2026-08-21', method: 'cash', settlements: [{ obligationId: 'obligation:daily:su-day', wageSatang: 35_000 }] });
  await assert.rejects(postLaborV2PaymentSession(db, { paymentDate: '2026-08-22', settlements: [{ obligationId: 'obligation:contract:bags', wageSatang: 1 }] }), /unavailable or unpriced/, 'an open unpriced contract cannot be paid');
  const contractObligation = await finalizeLaborContractBatchV2(db, openContract, { finalizedAt: '2026-08-23', finalization: { kind: 'quantity_rate', quantityMilli: 4_125_000, rateSatang: 100, unitLabel: 'ถุง' } });
  await recordLaborDayV2(db, { workDate: '2026-08-24', tasks: [{ id: 'h-su-a', title: 'เก็บกิ่ง', assigneePersonIds: [su] }, { id: 'h-su-b', title: 'ขนของ', assigneePersonIds: [su] }, { id: 'h-chon', title: 'ล้างถัง', assigneePersonIds: [chon] }], hourly: [{ id: 't1', taskId: 'h-su-a', personId: su, rateSatang: 12_000, durationMinutes: 60 }, { id: 't2', taskId: 'h-su-b', personId: su, rateSatang: 12_000, durationMinutes: 90 }, { id: 't3', taskId: 'h-chon', personId: chon, rateSatang: 12_000, durationMinutes: 30 }] });
  const advance = await createLaborV2PersonAdvance(db, { id: 'su-advance', personId: su, advanceDate: '2026-08-24', amountSatang: 10_000 }); const chonAdvance = await createLaborWorkerAdvance(db, { id: 'chon-advance', personId: chon, advanceDate: '2026-08-24', amountSatang: 10_000 }); assert.deepEqual((await listLaborV2PersonAdvances(db, su)).map((item) => item.id), [advance], 'V2 person-finance lists the shared advance without a v1 wage/payable route');
  await postLaborV2PaymentSession(db, { paymentDate: '2026-08-24', settlements: [{ obligationId: 'obligation:hourly:hourly:su|2026-08-24|12000|', wageSatang: 20_000, bonusSatang: 1_000, advanceRecoveries: [{ advanceId: advance, amountSatang: 5_000 }] }] });
  read = await getLaborV2ReadModel(db); assert.deepEqual(read.obligations.filter((item) => item.sourceKind === 'hourly').map((item) => [item.personId, item.dueSatang, item.remainingSatang]).sort(), [[chon, 6_000, 6_000], [su, 30_000, 10_000]], 'uneven hourly workers remain independent; bonus/recovery do not mutate wage earned');
  const extraAdvanceA = await createLaborWorkerAdvance(db, { id: 'su-extra-a', personId: su, advanceDate: '2026-08-24', amountSatang: 6_000 }); const extraAdvanceB = await createLaborWorkerAdvance(db, { id: 'su-extra-b', personId: su, advanceDate: '2026-08-24', amountSatang: 6_000 }); const beforeRejected = await db.getAllAsync<{ sessions: number; settlements: number }>('SELECT (SELECT count(*) FROM labor_v2_payment_sessions) sessions, (SELECT count(*) FROM labor_v2_payment_recipient_settlements) settlements'); await assert.rejects(postLaborV2PaymentSession(db, { id: 'duplicate-obligation', paymentDate: '2026-08-25', settlements: [{ obligationId: 'obligation:hourly:hourly:chon|2026-08-24|12000|', wageSatang: 4_000 }, { obligationId: 'obligation:hourly:hourly:chon|2026-08-24|12000|', wageSatang: 4_000 }] }), /cannot include an obligation more than once/, 'duplicate same-session allocations reject before a write'); await assert.rejects(postLaborV2PaymentSession(db, { id: 'cross-person-recovery', paymentDate: '2026-08-25', settlements: [{ obligationId: 'obligation:hourly:hourly:su|2026-08-24|12000|', wageSatang: 1_000, advanceRecoveries: [{ advanceId: chonAdvance, amountSatang: 1_000 }] }] }), /same person obligation/, 'cross-person advance recovery rejects'); await assert.rejects(postLaborV2PaymentSession(db, { id: 'recovery-over-wage', paymentDate: '2026-08-25', settlements: [{ obligationId: 'obligation:hourly:hourly:su|2026-08-24|12000|', wageSatang: 10_000, bonusSatang: 50_000, advanceRecoveries: [{ advanceId: extraAdvanceA, amountSatang: 6_000 }, { advanceId: extraAdvanceB, amountSatang: 6_000 }] }] }), /total advance recovery cannot exceed wage allocation/, 'bonus never expands advance-recovery capacity'); assert.deepEqual(await db.getAllAsync<{ sessions: number; settlements: number }>('SELECT (SELECT count(*) FROM labor_v2_payment_sessions) sessions, (SELECT count(*) FROM labor_v2_payment_recipient_settlements) settlements'), beforeRejected, 'rejected input leaves no partial V2 payment rows');
  await assert.rejects(postLaborV2PaymentSession(db, { paymentDate: '2026-08-25', settlements: [{ obligationId: contractObligation, wageSatang: 1, advanceRecoveries: [{ advanceId: advance, amountSatang: 1 }] }] }), /group obligation/, 'group obligations cannot recover advances');
  await postLaborV2PaymentSession(db, { paymentDate: '2026-08-25', method: 'cash', settlements: [{ obligationId: contractObligation, wageSatang: 412_500 }] }); assert.deepEqual(await listOpenLaborContractBatchesV2(db), [], 'finalized contract leaves the open-work projection and remains one group obligation');
  await assert.rejects(postLaborV2PaymentSession(db, { paymentDate: '2026-08-25', settlements: [{ obligationId: 'obligation:hourly:hourly:chon|2026-08-24|12000|', wageSatang: 6_001 }] }), /cannot exceed/, 'over-allocation fails atomically');
  await assert.rejects(postLaborV2PaymentSession(db, { paymentDate: '2026-08-25', settlements: [{ obligationId: 'obligation:hourly:hourly:su|2026-08-24|12000|', wageSatang: 1_000, advanceRecoveries: [{ advanceId: advance, amountSatang: 6_000 }] }] }), /cannot exceed wage allocation/, 'a recovery cannot exceed its explicit V2 wage allocation');
  await correctLaborV2PaymentSession(db, dailyPayment, { reason: 'แก้ช่องทางจ่าย', method: 'transfer' }); read = await getLaborV2ReadModel(db); assert.equal(read.payments.find((item) => item.id === dailyPayment)?.currentRevision, 2, 'reasoned correction appends revision without replacing payment identity'); assert.equal(read.events.filter((item) => item.entityId === dailyPayment).map((item) => item.action).join(','), 'posted,corrected', 'payment history is append-only'); const [today, calendar, history, person, unpaid, money] = await Promise.all([getLaborV2Today(db, '2026-08-21'), getLaborV2Calendar(db, '2026-08-21', '2026-08-24'), getLaborV2History(db), getLaborV2Person(db, su), getLaborV2Unpaid(db), getLaborV2MoneyHistory(db)]); assert.equal(today.tasks.length, 3, 'today stays V2 work-task based'); assert.equal(calendar.days[0]?.taskCount, 3, 'calendar counts task facts'); assert.ok(history.length && person.tasks.length && unpaid.length && money.length, 'typed V2 history/person/unpaid/money projections are available without v1 reads');
  console.log('LABOR_COMPENSATION_V2_COMMAND_PASS: V2 work, obligations, payments, recoveries, revisions, and projections remain separate from v1');
} finally { connection?.close(); await rm(directory, { recursive: true, force: true }); } };
main().catch((error: unknown) => { console.error(error); process.exit(1); });
